/*
 * Copyright © 2022 92AK
 */

-- DECLARATION
CREATE TABLE DBO.PearlZipPackageProvider(
      id INT GENERATED BY DEFAULT AS IDENTITY,
      providerName VARCHAR(255) NOT NULL,
      about VARCHAR(5000) NOT NULL,
      PRIMARY KEY(id)
);

-- PERMISSIONS
GRANT SELECT ON DBO.PearlZipPackageProvider TO PUB;
