/*
 * Copyright © 2022 92AK
 */

-- DEFINITION
CREATE VIEW PUB.PearlZipNotifications AS
SELECT p.id, Topic, Message, CreationTimestamp
FROM DBO.PEARLZIPNOTIFICATIONS p
INNER JOIN DBO.TOPIC t
ON p.TOPICID  = t.ID
ORDER BY CreationTimestamp DESC

-- PERMISSIONS
GRANT SELECT ON PUB.PEARLZIPNOTIFICATIONS TO APP;
